name: CI

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.2.0
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v2.1.5
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec
