name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: linkybits_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Map tcp port 5432 on service container to the host
          # Now Lucky can access it at localhost:5432 instead of postgres:5432
          # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.2.0
      - name: Install shards
        run: shards install
      - name: Install yarn packages
        run: yarn install --frozen-lockfile --no-progress
      - name: Compile assets
        run: yarn prod
      - name: Run tests
        run: crystal spec
